### PR TITLE
Update Prettier

### LINKED ISSUE #148: Update Prettier

### PR DESCRIPTION
**Pull request by jherdman**
Resolves #148

### CODE REVIEW

**Comment by jherdman** [comment]
@MelSumner this should be good to go

**Comment by MelSumner** [comment]
@jherdman looks like it needs a bit of a rebase. 👍

**Comment by jherdman** [comment]
@MelSumner rebased and ready!

**Review by MelSumner — APPROVED** [review]
Thank you for doing this work!

**Pull request merged**
