### PR TITLE
Bump ember-inflector version

### PR DESCRIPTION
**Pull request by gilest**
I've had this version pinned for a while without issue 🤷‍♂️

### CODE REVIEW

**Comment by camerondubas** [comment]
I would also like to see this bumped 👍

**Comment by jherdman** [comment]
This should be resolved now on the master branch.

**Comment by gilest** [comment]
Thanks @jherdman !

Look forward to the next release 🙌

**Comment by jherdman** [comment]
Absolutely!

**Comment by jherdman** [comment]
@robertpbaxter resolved in #157

**Pull request closed without merging**
